- name: install utils
  ansible.builtin.package:
    name:
      - curl
      - arp-scan
      - meld
      - htop
      - glances
      - jq
      - plocate
      - trash-cli
    state: present
    update_cache: yes
  become: yes
